# Site settings
title: Data Analysis Projects
author:
  name: Dora Rippon
  email: rippondora@gmail.com
  linkedin: www.linkedin.com/in/dora-rippon

description: "A diverse collection of projects showcasing programming and data analysis skills"

# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
