# Site settings
title: Data Analysis Projects
author:
  name: Dora Rippon
  email: rippondora@gmail.com
description: "A diverse collection of projects showcasing programming and data analysis skills"

# Build settings
remote_theme: jekyll/cayman
